Search_Engine/search_engine/search_engine/urls.py
from django.conf.urls import url
from django.contrib import admin
from practice import views
from .views import AjaxData, scrape, scrape_result,look_up, look_up_result

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^practice_list/$', views.practice_list, name='practice_list'),
    url(r'^practice_add/$', views.practice_add, name='practice_add'),
    url(r'^practice_edit/(\d+)/', views.practice_edit, name='practice_edit'),
    url(r'^practice_delete/(\d+)/', views.practice_delete, name='practice_delete'),
    url(r'^api/ajax/data/$', AjaxData.as_view()),
    url(r'^scrape/$', scrape, name='scrape'),
    url(r'^scrape_result/$', scrape_result, name='scrape_result'),
    url(r'^look_up/$', look_up, name='look_up'),
    url(r'^look_up_result/$', look_up_result, name='look_up_result'),
]

Search_Engine/search_engine/search_engine/forms.py
from django import forms

SEED_URL_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'Enter Seed URL: e.x. https://www.yahoo.co.jp'}
MAX_DEPTH_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'Enter Maximum Depth: e.x. 2'}
MAX_CAPACITY_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'Enter Maximum Capacity: e.x. 100'}
TARGET_HTML_TAG_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'Enter Target HTML Tag: e.x. h1'}
QUERY_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'Enter Seed URL: e.x. やきいも'}


class ScrapingForm(forms.Form):
    seed_url = forms.CharField(label='', widget=forms.TextInput(attrs=SEED_URL_ATTRIBUTE))
    max_depth = forms.IntegerField(label='', min_value=0, widget=forms.NumberInput(attrs=MAX_DEPTH_ATTRIBUTE))
    max_capacity = forms.IntegerField(label='', min_value=0, widget=forms.NumberInput(attrs=MAX_DEPTH_ATTRIBUTE))
    target_html_tag = forms.CharField(label='', widget=forms.TextInput(attrs=TARGET_HTML_TAG_ATTRIBUTE))


class LookUpForm(forms.Form):
    query = forms.CharField(label='', widget=forms.TextInput(attrs=QUERY_ATTRIBUTE))

Search_Engine/search_engine/templates/look_up.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>検索画面</title>
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
	/* ----------------- CSS Reset -------------------*/
        html, body,
        ul, ol, li,
        h1, h2, h3, h4, h5, h6, p, div {
            margin: 0;
            padding: 0;
        }
        li {
            list-style: none;
        }
        a {
            text-decoration: none;
        }

    /* ----------------- Search Style -------------------*/
		#engine-title{
			padding-top: 128px;
			padding-bottom: 8px;
			text-align: center;
		}
        #btn-wrapper{
            text-align: center;
            padding-top: 24px;
        }
        #btn-wrapper a{
            color: black;
        }
        #btn-wrapper a:hover{
            text-decoration: none
        }
        #render-with-search-wrapper{
            display: none;
            border: 1px solid black;
            background-color: white;
            z-index: 10;
        }
	</style>
</head>
<body>

	<div class="container">
		<h1 id="engine-title">Search Me!</h1>
		<form action="{% url 'look_up_result' %}" method="post">
			{% csrf_token %}
			<div class="row">
				<div class="col-sm-9">
					{{ form }}
				</div>
				<div class="col-sm-3">
					<input type="submit" value="Search" class="form-control">
				</div>
			</div>
            <div class="row">
              <div class="col-sm-8" id="render-with-search-wrapper">
                <ul id="render-with-search">

                </ul>
              </div>
            </div>
		</form>
		<div id="btn-wrapper">
			<button class="btn btn-default" id=>
				<a href="{% url 'scrape' %}">Collect Targets</a>
			</button>
			<button class="btn btn-default" id=>
				<a href="">Manage Indexes</a>
			</button>
		</div>
	</div>

	<script>
      $(function(){
        var endpoint = '/api/ajax/data/';
        $('#id_query').on('keyup', function(){
          query = $(this).val();
          if(query.length == 0){
            $('#render-with-search-wrapper').hide()
          }else{
            $('#render-with-search-wrapper').show();
          }

          $.ajax({
            method: "GET",
            url: endpoint + '?' + 'params1=' + query,
            success: function(data){
              $('#render-with-search').empty();
              counter = 0;
              for(var key in data){
                target = Object.keys(data[key]);
                $('#render-with-search').append('<li>' + target + '</li>');
                counter ++;
                if(counter == 10) break;
              }
            },
            error: function(data){
                console.log('Error');
            }
          });
        });
        /*
          $.each(data, function(i, d){
            $('#render-with-search').append('<li>' + d + '</li>');
            if(i == 10) return false;
          });
        */
      });
	</script>

</body>
</html>

Search_Engine/search_engine/templates/look_up_result.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>検索結果</title>
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <style>
	/* ----------------- CSS Reset -------------------*/
        html, body,
        ul, ol, li,
        h1, h2, h3, h4, h5, h6, p, div {
            margin: 0;
            padding: 0;
        }
        li {
            list-style: none;
        }
        a {
            text-decoration: none;
        }
        #search-engine{
            margin: 24px 16px;
            clear:both;
        }
        #search-engine h1{
            text-align: center;
            margin-bottom: 8px;
        }
        #render-with-search-wrapper{
            display: none;
            border: 1px solid black;
            background-color: white;
        }
        .url-wrapper{
            margin: 24px 32px;
        }
	</style>
</head>
<body>
  <div class="container">
    <div id="search-engine">
      <h1><a href="{% url 'look_up' %}">Top</a></h1>
		<form action="{% url 'look_up_result' %}" method="post">
			{% csrf_token %}
			<div class="row">
				<div class="col-sm-9">
					{{ form }}
				</div>
				<div class="col-sm-3">
					<input type="submit" value="Search" class="form-control">
				</div>
			</div>
            <div class="row">
              <div class="col-sm-8" id="render-with-search-wrapper">
                <ul id="render-with-search">

                </ul>
              </div>
            </div>
		</form>
    </div>

    <div id="result-wrapper">
      {% for url, title in items.items %}
          <div class="url-wrapper">
            <h4><a href="{{ url }}">{{ title }}</a></h4>
            <p><small>url: {{ url }}</small></p>
          </div>
      {% endfor %}
    </div>
  </div>

  <div id="indexes"> </div>

  <script>
      $(function(){
        var endpoint = '/api/ajax/data/';
        $('#id_query').on('keyup', function(){
          query = $(this).val();
          if(query.length == 0){
            $('#render-with-search-wrapper').hide()
          }else{
            $('#render-with-search-wrapper').show();
          }

          $.ajax({
            method: "GET",
            url: endpoint + '?' + 'params1=' + query,
            success: function(data){
              $('#render-with-search').empty();
              counter = 0;
              for(var key in data){
                target = Object.keys(data[key]);
                $('#render-with-search').append('<li>' + target + '</li>');
                counter ++;
                if(counter == 10) break;
              }
            },
            error: function(data){
                console.log('Error');
            }
          });
        });
        /*
          $.each(data, function(i, d){
            $('#render-with-search').append('<li>' + d + '</li>');
            if(i == 10) return false;
          });
        */
      });
  </script>

</body>
</html>

Search_Engine/search_engine/templates/scrape.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>スクレイプ</title>
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <style>
	/* ----------------- CSS Reset -------------------*/
        html, body,
        ul, ol, li,
        h1, h2, h3, h4, h5, h6, p, div {
            margin: 0;
            padding: 0;
        }
        li {
            list-style: none;
        }
        a {
            text-decoration: none;
        }

    /* ----------------- Scraping Style -------------------*/
        #search-engine{
            margin: 0 auto;
            width: 80%;
        }

        #title {
            margin-top: 24px;
        }

        #form-wrapper{
            width: 80%;
            margin: 16px auto;
        }

        #form-wrapper input{
            margin-bottom: 8px;
        }

        #submit{
            width: 40%;
            margin: 0 auto;
        }

        #button-wrapper{
            text-align: center;
            margin: 0 auto;
        }
	</style>
</head>
<body>

<div id="scraping-wrapper">
    <div id="title">
        <h1 class="text-center">スクレイピング道場</h1>
    </div>
    <div id="form-wrapper">
        <form action="" method="post">
            {% csrf_token %}
            <div id="scraping-form">
                {{ form.as_p }}
            </div>
            <input type="submit" value="Scrape" class="form-control" id="submit">
        </form>
    </div>

    <div id="button-wrapper">
        <p class="btn btn-danger">Add HTML Tag</p>
    </div>
</div>


<script>
    $(function(){
        var new_input = '<p><input type="text" name="target_html_tag" placeholder="Enter Target HTML Tag: e.x. h1" class="form-control" id="id_target_html_tag" required></p>'
        $('.btn').on('click', function(){
            console.log(new_input);
            $('#scraping-form').append(new_input);
        });
    })
</script>
</body>
</html>

Search_Engine/search_engine/templates/scrape_result.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>スクレイプ結果</title>
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<title>PMT login</title>
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <style>
	/* ----------------- CSS Reset -------------------*/
        html, body,
        ul, ol, li,
        h1, h2, h3, h4, h5, h6, p, div {
            margin: 0;
            padding: 0;
        }
        li {
            list-style: none;
        }
        a {
            text-decoration: none;
        }

    /* ----------------- Scraping Style -------------------*/

        .value-wrapper{
            margin-left: 24px;
        }




	</style>
</head>
<body>

<h1 class="text-center">Result of Index</h1>
{% for key, urls in index.items %}
    <div class="container">
        <h4 class="text-left">{{ key }}</h4>
        <ul class="value-wrapper">
            {% for url, title in urls.items %}
                <li>{{ title }} : {{ url }}</li>
            {% endfor %}
        </ul>
    </div>
{% endfor %}


<h1 class="text-center">Result of Graph</h1>
{% for key, values in graph.items %}
    <div class="container">
        <h4 class="text-left">{{ key }}</h4>
        <ul class="value-wrapper">
            {% for value in values %}
                <li>{{ value }}</li>
            {% endfor %}
        </ul>
    </div>
{% endfor %}


</body>
</html>