Search_Engine/search_engine/search_engine/urls.py
from django.conf.urls import url
from django.contrib import admin
from practice import views
from .views import AjaxData, scrape, scrape_result,look_up, look_up_result

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^practice_list/$', views.practice_list, name='practice_list'),
    url(r'^practice_add/$', views.practice_add, name='practice_add'),
    url(r'^practice_edit/(\d+)/', views.practice_edit, name='practice_edit'),
    url(r'^practice_delete/(\d+)/', views.practice_delete, name='practice_delete'),
    url(r'^api/ajax/data/$', AjaxData.as_view()),
    url(r'^scrape/$', scrape, name='scrape'),
    url(r'^scrape_result/$', scrape_result, name='scrape_result'),
    url(r'^look_up/$', look_up, name='look_up'),
    url(r'^look_up_result/$', look_up_result, name='look_up_result'),
]

Search_Engine/search_engine/practice/models.py
from django.db import models
'''
POSITION = (
    ('Pitcher', 'pitcher'),
    ('Catcher', 'catcher'),
    ('Infielder', 'infielder'),
    ('Outfielder', 'outfielder')
)

TEAM = (
    ('A', 'a'),
    ('B', 'b'),
    ('C', 'c'),
)


class Team(models.Model):
    name = models.CharField('球団名', max_length=32, choices=TEAM)

    def __str__(self):
        return self.name + str(self.pk)

    class Meta:
        verbose_name = verbose_name_plural = '球団'
'''


class BaseballPlayer(models.Model):
    name = models.CharField('選手名', max_length=32)
    yearly_pay = models.IntegerField('年棒')
    position = models.CharField('守備位置', max_length=32)
    team = models.CharField('球団名', max_length=32)
    # team = models.ForeignKey(Team)

    def __str__(self):
        return self.name + '@' + self.team

    class Meta:
        verbose_name = verbose_name_plural = '選手'

Search_Engine/search_engine/practice/forms.py
from django import forms
from .models import BaseballPlayer #, Team


NAME_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'Enter your name -> ex: Taro Tanaka'}
YEARLY_PAY_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'Enter your yearly pay'}
YEARLY_PAY_MAX_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'enter maximum yearly pay'}
YEARLY_PAY_MIN_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'enter minimum yearly pay'}
POSITION_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'Enter your position'}
TEAM_ATTRIBUTE = {'class': 'form-control', 'placeholder': 'Enter your team'}


class BaseballPlayerAddForm(forms.ModelForm):
    name = forms.CharField(label='', widget=forms.TextInput(attrs= NAME_ATTRIBUTE))
    yearly_pay = forms.IntegerField(min_value=1, label='', widget=forms.NumberInput(attrs=YEARLY_PAY_ATTRIBUTE))
    position = forms.CharField(label='', widget=forms.TextInput(attrs= POSITION_ATTRIBUTE))
    team = forms.CharField(label='', widget=forms.TextInput(attrs= TEAM_ATTRIBUTE))
    # position = forms.ChoiceField(label='', choices= POSITION, widget=forms.Select(attrs=POSITION_ATTRIBUTE))
    # team = forms.ModelChoiceField(label='', queryset=Team.objects.all(), widget=forms.Select(attrs=TEAM_ATTRIBUTE))

    class Meta:
        model = BaseballPlayer
        fields = ('name', 'yearly_pay', 'position', 'team')


class BaseballPlayerSearchForm(forms.ModelForm):
    name = forms.CharField(label='', widget=forms.TextInput(attrs= NAME_ATTRIBUTE), required=False)
    yearly_pay_min = forms.IntegerField(min_value=1, label='', widget=forms.NumberInput(attrs=YEARLY_PAY_MIN_ATTRIBUTE), required=False)
    yearly_pay_max = forms.IntegerField(min_value=1, label='', widget=forms.NumberInput(attrs=YEARLY_PAY_MAX_ATTRIBUTE), required=False)
    position = forms.CharField(label='', widget=forms.TextInput(attrs= POSITION_ATTRIBUTE), required=False)
    team = forms.CharField(label='', widget=forms.TextInput(attrs= TEAM_ATTRIBUTE), required=False)

    class Meta:
        model = BaseballPlayer
        fields = ('name', 'position', 'team')

    def filter_players(self, players):
        if self.is_valid():
            name = self.cleaned_data.get('name')
            yearly_pay_min = self.cleaned_data.get('yearly_pay_min')
            yearly_pay_max = self.cleaned_data.get('yearly_pay_max')
            position = self.cleaned_data.get('position')
            team = self.cleaned_data.get('team')

            if name:
                players = players.filter(name__contains=name)
            if yearly_pay_min:
                players = players.filter(yearly_pay__gte=yearly_pay_min)
            if yearly_pay_max:
                players = players.filter(yearly_pay__lte=yearly_pay_max)
            if position:
                players = players.filter(position=position)
            if team:
                players = players.filter(team=team)
            return players
        else:
            return players

Search_Engine/search_engine/practice/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect, Http404
from .forms import BaseballPlayerAddForm, BaseballPlayerSearchForm
from .models import BaseballPlayer


def practice_list(request):
    # Viewに表示するために、DBに格納されている野球選手を全て取得
    players = BaseballPlayer.objects.all()

    # 野球選手検索用のformを作成し、もし検索条件用のQuery情報が送られてきたならばfilter_player_functionに情報を渡してDBで条件を絞り込む
    form = BaseballPlayerSearchForm(request.GET)
    players = form.filter_players(players)

    # 野球選手を表示するためのViewをPaginatorを使って分割し、もし例外が発生しそうなら、1ページ目を返す
    # 検索条件用のQuery情報があった場合に、その情報をPaginatorに引き継ぐためにrequest.GETからpage以外のparameter情報を取得してViewに渡す
    paginator = Paginator(players, 5)
    params = request.GET.copy()
    if 'page' in params:
        page = params['page']
        del params['page']
    else:
        page = 1

    search_params = params.urlencode()    # urlencode()はクエリーパラメーターの文字列に変換するメソッド

    try:
        players = paginator.page(page)
    except (PageNotAnInteger, EmptyPage):
        players = paginator.page(1)

    # practice_list.htmlで実際に使われる情報をdに格納する
    d = {
        'form': form,
        'players': players,
        'search_params': search_params,
    }
    return render(request, 'practice/practice_list.html', d)


def practice_add(request):

    # もしrequest.methodがPOSTなら、Query情報をクリーニングしてDBに格納する
    if request.method == 'POST':
        form = BaseballPlayerAddForm(request.POST or None)
        if form.is_valid():
            # print(form.cleaned_data)
            # {'name': 'TPON', 'team': <Team: A1>, 'position': 'Outfielder', 'yearly_pay': 1000}
            name = form.cleaned_data.get('name')
            team = form.cleaned_data.get('team')
            count = BaseballPlayer.objects.filter(team=team).filter(name__contains=name).count()

            if count == 0:
                form.save()
                return HttpResponseRedirect(reverse('practice_list'))

    form = BaseballPlayerAddForm()

    d = {
        'form': form,
    }
    return render(request, 'practice/practice_add.html', d)
    # print(request.POST)
    # <QueryDict: {'name': ['SODA'], 'csrfmiddlewaretoken': ['CMT7k0f0ZAXK7sgrNwe2n5O4mQO4rRGxJ1Jb8L0E5RnGHmTBmCwW8igRWRpVNjkm'], 'position': ['Catcher'], 'yearly_pay': ['1000']}>
    # print(request.POST['name'])
    # SODA
    # print(request.POST['position'])
    # ['Catcher']


def practice_edit(request, id):
    try:
        player = BaseballPlayer.objects.get(id=id)
    except BaseballPlayer.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        form = BaseballPlayerAddForm(request.POST, instance=player)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('practice_list'))

    form = BaseballPlayerAddForm(instance=player)
    d = {
        'form': form
    }
    return render(request, 'practice/practice_edit.html', d)


def practice_delete(request, id):
    try:
        player = BaseballPlayer.objects.get(id=id)
    except BaseballPlayer.DoesNotExist:
        raise Http404

    player.delete()
    return HttpResponseRedirect(reverse('practice_list'))

Search_Engine/search_engine/templates/practice/practice_add.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Practice</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        #form-wrapper{
           width: 40%;
           margin: 100px auto;
        }
    </style>
</head>
<body>

<h2 class="text-right">
    <a href="{% url 'practice_list' %}">選手リストへ</a>
</h2>

<div id="form-wrapper">
    <form action="{% url 'practice_add' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="送信" class="form-control">
    </form>
</div>

<script>
    $(function(){
        // $('#id_name').addClass('form-control');
        // $('#id_yearly_pay').addClass('form-control');
        // $('#id_position').addClass('form-control');
        // $('#id_team').addClass('form-control');
    })
</script>

</body>
</html>

Search_Engine/search_engine/templates/practice/practice_edit.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Practice</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        #form-wrapper{
           width: 40%;
           margin: 100px auto;
        }
    </style>
</head>
<body>

<h2 class="text-right">
    <a href="{% url 'practice_list' %}">選手リストへ</a>
</h2>

<div id="form-wrapper">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="送信" class="form-control">
    </form>
</div>
</body>
</html>

Search_Engine/search_engine/templates/practice/practice_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        #info-wrapper{
            width: 60%;
            margin: 48px auto;
        }
        #paginator-wrapper{
            width: 60%;
            margin: 0 auto;
        }
    </style>
</head>
<body>

<h2 class="text-right">
    <a href="{% url 'practice_add' %}">選手を追加する</a>
</h2>

<div class="container">
    <h2 class="text-center">選手を探す</h2>
    <form action="" method="get">
        {{ form.as_p }}
        <input type="submit" class="form-control" value="Search">
    </form>
</div>

<div id="info-wrapper">
    {% for player in players %}
        <ul class="list-group text-center">
            <li class="list-group-item">TEAM: {{ player.team }}</li>
            <li class="list-group-item">PLAYER: {{ player.name }}</li>
            <li class="list-group-item">PAY: {{ player.yearly_pay }}</li>
            <li class="list-group-item">POSITION: {{ player.position }}</li>
            <li class="list-group-item"><a href="{% url 'practice_edit' player.id %}">編集する</a></li>
            <li class="list-group-item"><a href="{% url 'practice_delete' player.id %}">退団させる</a></li>
        </ul>
    {% endfor %}
</div>


<div id="paginator-wrapper">
<!-- Pagination機能 -->
    {% if players.has_previous %}
        <a href="?page={{ players.previous_page_number }}&{{ search_params }}">&lt; 前のページ</a>
    {% else %}
        <span>&lt; 前のページ</span>
    {% endif %}

    {{ players.number }}ページ

    {% if  players.has_next %}
        <a href="?page={{ players.next_page_number }}&{{ search_params }}">次のページ &gt;</a>
    {% else %}
        <span>次のページ &gt;</span>
    {% endif %}
</div>


</body>
</html>